apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: test

spec:
  type: ClusterIP
  selector:
     app: jar
  
  ports:
   - protocol: TCP
     port: 1077
     targetPort: 8080
